alias ll='ls --color -al'
alias trial='trial yamls.android.master_tests.test_master_cfg_prod'
alias tree='tree -C'
alias cdyaml='cd /data/mickaelm/buildbot/yamls/android'
alias ldap='txw ldap-get-group-emails'
